[package]
name = "orbitus"
version = "0.0.1"
edition = "2021"

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
clap = { version = "4.5.8", features = ["derive"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[lints]
workspace = true
