[package]
name = "orbitus"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
clap = { version = "4.5.8", features = ["derive"] }
tokio = { workspace = true }

[lints]
workspace = true
